// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/","parentId":"1","id":"2"},"3":{"path":"/vuln","parentId":"1","id":"3"},"4":{"path":"/vuln/:id","parentId":"1","id":"4"},"5":{"path":"/approval","parentId":"1","id":"5"},"6":{"path":"/approval/:id","parentId":"1","id":"6"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__vuln__index" */'@/pages/vuln/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__vuln__id" */'@/pages/vuln/[id].tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__approval__index" */'@/pages/approval/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__approval__id" */'@/pages/approval/[id].tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'D:/Code/Projects/Vuln/src/layouts/index.tsx')),
},
  };
}
